{% set name = "python-arango" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6948fcb0d5933a31e823e70d970a22e1aa8489ac89368e74c5aecefe150ece9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm >=3.4
  run:
    - python >=3
    - setuptools >=42
    - setuptools_scm >=3.4
    - requests
    - six
    - requests-toolbelt
    - pyjwt

about:
  home: https://github.com/joowani/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/joowani/python-arango

extra:
  recipe-maintainers:
    - carlodri
