{% set name = "python-arango" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04dbb017945105925c01d05ac98a62d718d29586cf39ef85ae3a44f032923b1c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - six
    - requests-toolbelt
    - pyjwt

about:
  home: https://github.com/joowani/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/joowani/python-arango

extra:
  recipe-maintainers:
    - carlodri
