{% set name = "python-arango" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 830e1994b2cc2f323072dffe5a4aeaa194dbf369090f102348aea87a647cc767

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - six
    - requests-toolbelt

about:
  home: https://github.com/joowani/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/joowani/python-arango

extra:
  recipe-maintainers:
    - carlodri
