{% set name = "python-arango" %}
{% set version = "7.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0725a453d46996396e4740e84ead32b36186e853a545044411fb7f624a1b71b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyjwt
    - requests
    - requests-toolbelt
    - setuptools >=42

about:
  home: https://github.com/ArangoDB-Community/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/ArangoDB-Community/python-arango

extra:
  recipe-maintainers:
    - carlodri
    - aMahanna
    - xylar
