{% set name = "python-arango" %}
{% set version = "7.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea3f581816c6b39fe02d71c5a054aeba5aaa253cae3ffbf52ffc0d744d51a65d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm >=3.4
  run:
    - python >=3
    - setuptools >=42
    - setuptools_scm >=3.4
    - requests
    - urllib3 >=1.26.0
    - six
    - requests-toolbelt
    - pyjwt

about:
  home: https://github.com/joowani/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/joowani/python-arango

extra:
  recipe-maintainers:
    - carlodri
