{% set name = "python-arango" %}
{% set version = "7.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-arango-{{ version }}.tar.gz
  sha256: 028b973bc865df9a18cb9d7f95de79b43d6bdb84320d4285d53b4de01c0313dd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyjwt
    - requests
    - requests-toolbelt
    - setuptools >=42

about:
  home: https://github.com/ArangoDB-Community/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/ArangoDB-Community/python-arango

extra:
  recipe-maintainers:
    - xylar
    - carlodri
    - aMahanna
    - xylar
